07/27/2024 06:04:39 PM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/black/bodies/body_25_refine_3_6.py", line 205, in <module>
    aux = self.visit_default(leaf)
TypeError: <lambda>() takes 1 positional argument but 2 were given
Command exited with non-zero status 1
1.58user 4.18system 0:00.85elapsed 675%CPU (0avgtext+0avgdata 106104maxresident)k
0inputs+192outputs (4major+24602minor)pagefaults 0swaps
