07/27/2024 08:57:34 PM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/black/bodies/body_155_initial_8.py", line 28, in <module>
    first_line = next((leaf.lineno for leaf in self.leaves if leaf.lineno != 0), 0)
  File "./popular_projects_snippets_dataset/black/bodies/body_155_initial_8.py", line 28, in <genexpr>
    first_line = next((leaf.lineno for leaf in self.leaves if leaf.lineno != 0), 0)
AttributeError: 'dict' object has no attribute 'lineno'
Command exited with non-zero status 1
1.60user 4.12system 0:00.82elapsed 691%CPU (0avgtext+0avgdata 108664maxresident)k
0inputs+16outputs (0major+25390minor)pagefaults 0swaps
