07/28/2024 10:55:58 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_133_guide_8_1.py", line 84, in <module>
    raise
RuntimeError: No active exception to reraise
Command exited with non-zero status 1
1.65user 4.83system 0:00.76elapsed 847%CPU (0avgtext+0avgdata 116860maxresident)k
0inputs+56outputs (1major+21509minor)pagefaults 0swaps
