07/28/2024 09:24:14 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_16_initial_0.py", line 30, in <module>
    ctx = _cv_app.get()
TypeError: <lambda>() takes 0 positional arguments but 1 was given
Command exited with non-zero status 1
1.53user 4.87system 0:00.67elapsed 947%CPU (0avgtext+0avgdata 107584maxresident)k
0inputs+48outputs (0major+24945minor)pagefaults 0swaps
