07/28/2024 10:09:32 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_23_refine_4_1.py", line 114, in <module>
    raise AssertionError(
AssertionError: Popped wrong request context. (<__main__.MockCtx object at 0x7f8b4533b550> instead of <__main__.Mock object at 0x7f8b485bd4c0>)
Command exited with non-zero status 1
1.61user 4.78system 0:00.67elapsed 943%CPU (0avgtext+0avgdata 108192maxresident)k
0inputs+128outputs (4major+25029minor)pagefaults 0swaps
