07/27/2024 03:08:08 PM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_350_refine_3_5.py", line 63, in <module>
    raise RuntimeError(
RuntimeError: Session backend did not open a session. Check the configuration
Command exited with non-zero status 1
1.52user 3.39system 0:01.09elapsed 447%CPU (0avgtext+0avgdata 80180maxresident)k
0inputs+80outputs (2major+17646minor)pagefaults 0swaps
