07/27/2024 05:51:17 PM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_361_guide_4_6.py", line 33, in <module>
    super().__init__(initial, on_update)
RuntimeError: super(): no arguments
Command exited with non-zero status 1
1.57user 3.81system 0:00.79elapsed 674%CPU (0avgtext+0avgdata 104888maxresident)k
0inputs+16outputs (1major+23941minor)pagefaults 0swaps
