07/28/2024 08:58:38 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_362_refine_3_4.py", line 23, in <module>
    aux = super().__getitem__(key)
RuntimeError: super(): no arguments
Command exited with non-zero status 1
1.67user 4.68system 0:00.67elapsed 949%CPU (0avgtext+0avgdata 107304maxresident)k
0inputs+24outputs (0major+24818minor)pagefaults 0swaps
