07/28/2024 11:14:24 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_357_guide_3_1.py", line 46, in <module>
    aux = super().invoke(cli, args, **kwargs)
TypeError: 'MockSuperInvoker' object is not callable
Command exited with non-zero status 1
1.74user 4.73system 0:00.76elapsed 850%CPU (0avgtext+0avgdata 117512maxresident)k
0inputs+48outputs (0major+21899minor)pagefaults 0swaps
