07/28/2024 09:39:09 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_347_refine_4_7.py", line 74, in <module>
    super().__init__(path, base_url, *args, **kwargs)
RuntimeError: super(): no arguments
Command exited with non-zero status 1
1.59user 4.79system 0:00.65elapsed 978%CPU (0avgtext+0avgdata 108084maxresident)k
0inputs+96outputs (0major+24943minor)pagefaults 0swaps
