07/28/2024 08:09:55 AM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_74_refine_2_6.py", line 14, in <module>
    super()._load_form_data()
RuntimeError: super(): no arguments
Command exited with non-zero status 1
1.52user 4.84system 0:00.65elapsed 974%CPU (0avgtext+0avgdata 106024maxresident)k
0inputs+16outputs (0major+24440minor)pagefaults 0swaps
