07/27/2024 03:10:48 PM Logging starts
Traceback (most recent call last):
  File "./popular_projects_snippets_dataset/flask/bodies/body_350_refine_6_2.py", line 53, in <module>
    outer_reqctx = _cv_request.get(None)
TypeError: <lambda>() takes 1 positional argument but 2 were given
Command exited with non-zero status 1
1.69user 3.99system 0:00.83elapsed 681%CPU (0avgtext+0avgdata 79608maxresident)k
0inputs+40outputs (0major+17608minor)pagefaults 0swaps
